### ISSUE TITLE
rendering screen

### ISSUE THREAD

**Issue by nikolodeon** [necauqua/subpocket#3] opened 2022-01-21 11:22 UTC
i'm getting this crash every time i use subpocket. it happens as soon as i open the subpocket inventory

crash report:
https://bytebin.lucko.me/TTB7UzBtcF

**Comment by necauqua** [comment] 2022-01-21 12:00
Based on the crash, you must've put some modded item inside of it - any ideas what it was?

**Comment by nikolodeon** [comment] 2022-01-21 12:31
> Based on the crash, you must've put some modded item inside of it - any ideas what it was?

ah i see. well i have a lot of mods installed that also have modded items. so its kinda hard to know for sure. what do you suggest i do? i cant open subpocket in order to take the modded item out as it just crashes when i do.

**Comment by necauqua** [comment] 2022-01-21 12:37
Actually, lucky for you, I think I fixed this, just found how my code can cause this exact crash given some modded item has some weird rendering.

I will push a commit with the fix and GitHub will build it and I'll give you a link to that build so you can test if it does actually fix the crash, gimme a few minutes

**Comment by nikolodeon** [comment] 2022-01-21 12:44
Oh wow that’s very nice :D I will first be able to test it later as I’m not by my pc right now. So you can take your time :)

**Comment by nikolodeon** [comment] 2022-01-22 13:41
Hey @necauqua did you manage to get a link so i can test it?

**Comment by necauqua** [comment] 2022-01-22 14:20
Hello, was fighting with gradle - the fix in code was there for a while (7c52105), but I'm trying to make it compile lul

I'll send it here once it finally works

**Comment by nikolodeon** [comment] 2022-01-22 15:01
ah no worries, dont stress. Just take your time :) i just thought maybe i hadn't seen it or something since you wrote that it would only take a few minutes

**Comment by necauqua** [comment] 2022-01-22 20:34
After a long while I finally fixed all the weird issues and nuked my maven and so on and so on, but I finally got a green build
https://github.com/necauqua/subpocket/actions/runs/1733990652

You need the artifact without any of the -api/-src/etc suffixes (it's inside of the subpocket-_hash_ zip)

**Comment by nikolodeon** [comment] 2022-01-23 17:12
alright. do i just replace the one i have in my mods folder with this new one? and do I first unzip the file before i use it?

**Comment by necauqua** [comment] 2022-01-23 17:28
Yes

The artifacts link at the bottom of the build page I sent is a zip with a few jars inside, you take the one without extra suffixes and replace your current one with that one

If it fixes the crash, an identical jar is going to be released on curse (and I guess I'll have to backport the fix for 1.16-1.17 as well), I am pretty sure it does

**Comment by nikolodeon** [comment] 2022-01-24 00:27
![A4D05563-97CD-4785-890F-2C660AD3E2B9](https://user-images.githubusercontent.com/97317637/150704624-a6a85f88-2b4b-45d8-975f-f3711936afbc.jpeg)
Alright I thought so. I just wanted to make sure before I messed it up or something.

anyways I’ve done what you said but now I’m getting another problem. All text has become boxes/squares..super weird (I’ll share a picture). So then I tried updating forge to the newest version, but that just gave me another crash even before entering into my world:
https://bytebin.lucko.me/fNApGBPdrh

**Comment by necauqua** [comment] 2022-01-24 02:18
Well, the crash after forge update is caused by the `supermartijn642corelib-1.0.16-mc1.18.jar`, whatever that is, reading the crash for you :)
So probably you'd want to downgrade back

The font issue is interesting though - I now realised that I was so sure this small crash fix would work that I never actually ran the game myself with it lol
Although I can't imagine how the hell that font thing happens xd

So I'll look into that and fix it too :)

Also yeah, does it at least fix the crash itself? Because fixing the fix is kind of worthless if the fix didn't work in the first place I guess

**Comment by nikolodeon** [comment] 2022-01-24 10:15
haha its a library mod for one of the mods i have. cant actually tell for which tho xD 
i tried downgrading back but then i just got a crash again. not sure if its the same one:
https://bytebin.lucko.me/Zg09Ocg51N

lol yea maybe you should try it out too :) 
awesome thanks!

thing is i cant test it because no matter what i do i cant get into my game to try it out :( so i dont know

**Comment by necauqua** [comment] 2022-01-24 10:42
Ok I just ran the game myself - had no issues whatsoever - and yeah I don't touch game menu fonts in any way _at all_, so I guess now you might have some weird unrelated issues, hope you find a fix for them since I need confirmation that the fix worked :)

Anyway, is that a modpack I can download?
Maybe the font issue is still somehow caused by some spooky weird interaction between the mods 🤷

And for the crash - it is the same - for some reason this `supermartijn642corelib` library is calling a deobfuscated method, which does not exist when running the game not from the development environment, no idea what happened there

**Comment by nikolodeon** [comment] 2022-01-24 14:52
okay well that's a good start! yea i hope i figure it out too! :)

no i put together my own modpack, unless i can somehow share it with you?
yea i think your right but i honestly dont see what it could be. it only happens when i have any forge version above 39.0.17. 

very odd.. should i give the crash report over to that mods developer maybe?

**Comment by necauqua** [comment] 2022-01-24 15:03
Can send it to me on [discord](https://discord.necauqua.dev) if you don't mind (like a zip of all mods or a multimc instance).

Well yeah, the crash is unrelated so you can ask that mod author why his mod crashes with higher forge versions, and here we can just run the older forge I guess.

So the font issue is there (no idea how I could've caused it) but does the subpocket crash when you open it now? (ignoring broken fonts obviously)

**Comment by nikolodeon** [comment] 2022-01-24 15:55
alright i joined your discord group. which part of the group do you want me to send it to? sorry if that's a dumb question, haven't used discord so much. 

alright ill send the crash report to the other mod developer.

i just tried another world (test world) and oddly I am able to join it without any problems... so wtf? so its only that one world that i can't join for some reason.

Also, it doesn't help to run in an older forge version, as I get those boxes that I showed you earlier. even if i guess correctly, by clicking buttons on screen, then it just gets stuck on the loading screen before entering the world..
so answering your last question; i cant actually know for certain if it works as nothing that i have tried so far helps to get into my game so i can try opening the subpocket.

**Comment by necauqua** [comment] 2022-01-24 16:09
Ah, the discord server was so that you can click on me (I should be pretty visible being an owner of the server) and send a DM

Yeah, that method that the mod lib thing tries to call is related to a tile entity, so a new world would not crash as it does not have that machine or whatever it is.

Oof, that's tough. So that's not only broken font but it also hangs.. Can you do just that again, wait for a few minutes on the loading screen, and then send me the entire `debug.log`?
Something's up, if we find out it's because of my mod - well great we found an issue before releasing the fix for the crash, if this is your modpack being weird - well then you got some help from me :)

**Comment by nikolodeon** [comment] 2022-01-24 16:34
ahhh i see. that makes sense

yeap pretty annoying! here is the debug file:
[debug.log](https://github.com/necauqua/subpocket/files/7927170/debug.log)

haha sounds like a win win for me :p

**Comment by necauqua** [comment] 2022-01-24 17:10
> it only happens when i have any forge version above 39.0.17

And then in the log there are those lines lol: `Mod cfm requires forge 39.0.45 or above`

And it's actually beyond my understanding how it didn't crash there and kept going lol

Nothing else was too out of the ordinary in the log sadly, at least that I can point at certain mods

**Comment by nikolodeon** [comment] 2022-01-25 11:45
aha i see.. well then i guess testing it below forge .45 won't work lol

yea i think it gave me a "crash" but then i could just click on the far left box on the screen and it would take me to the title screen. might have just been a warning since i was able to bypass it. but as the writing was just boxes i couldnt tell lol.

thats okay, cuz i actually got a breakthrough! found out it was "better furnaces reforged" mod that was the problem. so i deactivated that and i was able to enter the game. i then tried opening subpocket but got a crash again... sadly:
https://bytebin.lucko.me/n9vjTvmPjh

do you want more, like the last debug log or something as well?

**Comment by necauqua** [comment] 2022-01-25 11:53
Oops, nope, the crash is the same, looks like it wasn't fixed :(
Well now I have your modpack, so I'll try to replicate the crash - although I don't know what item causes that..
So the last (best) thing you can share is the playerdata from the save (`.minecraft/saves/<save_name>/playerdata/<uuid>.dat`) so that I copy ur subpocket contents to me when testing with ur mods

**Comment by necauqua** [comment] 2023-01-11 05:33
Ok a lot of things have happened over the time and I did not pinpoint/fix this issue properly;
but I made a new release for 1.18.2 which includes a crash handler, so even if some mod items are _weird_ - it would not crash the game and show a little notification that something is wrong.

In fact, I made this crash handler thing when thinking about this issue and then I never touched modding for almost a year for reasons.
Anyway, I'm closing this issue, feel free to open a new one if needed

**Closed as completed by necauqua** 2023-01-11 05:33 UTC
